Fix test
buttercomponents/butter-base-components pull request #5
Opened 2017-06-30 22:49 UTC by btzr-io

- Fix component test
- Fix button style
- Update styles

2017-07-01 21:55 UTC, xaiki requested changes
looks good, a few nitpicks

2017-07-01 21:55 UTC, xaiki commented on src/components/button/index.js
> +    }
we should probably add `prop-types` https://facebook.github.io/react/docs/typechecking-with-proptypes.html

2017-07-01 21:55 UTC, xaiki commented on src/components/switch/index.js
> +        this.apply = props.apply
i guess it's probably a good idea to: `this.apply = props.apply.bind(this)`

2017-07-01 21:55 UTC, xaiki commented on src/components/button/index.js
> +        this.apply = props.apply
i guess it's probably a good idea to: `this.apply = props.apply.bind(this)`

2017-07-01 21:55 UTC, xaiki commented on src/components/button/index.js
> -    GoBackButton: translate(['go-back-button'], {wait: true, withRef: true})(GoBackButton)
why kill GoBackButton ?

2017-07-01 21:55 UTC, xaiki commented on src/components/button/style.styl
>  .go-back
GoBackButton killed but CSS still present

2017-07-01 21:55 UTC, xaiki commented on src/components/dropdown/index.js
> +        this.apply = props.apply
i guess it's probably a good idea to: `this.apply = props.apply.bind(this)`

2017-07-02 01:18 UTC, btzr-io commented on src/components/button/index.js
> -    GoBackButton: translate(['go-back-button'], {wait: true, withRef: true})(GoBackButton)
here -> [src/components/navbar/index.js#L6](https://github.com/buttercomponents/butter-base-components/blob/master/src/components/navbar/index.js#L6)

2017-07-02 18:33 UTC, xaiki commented on src/components/button/index.js
> -    GoBackButton: translate(['go-back-button'], {wait: true, withRef: true})(GoBackButton)
ok i guess it makes sense

2017-07-02 18:37 UTC, xaiki approved these changes
left a small comment if you think it's ok you can merge

2017-07-02 18:37 UTC, xaiki commented on src/components/button/index.js
> +        type: PropTypes.string.isRequired,
i thinks `isRequired` means you **need** to pass it everytime, here we have it in default props

2017-07-02 18:39 UTC, xaiki commented
```The defaultProps will be used to ensure that this.props.name will have a value if it was not specified by the parent component. The propTypes typechecking happens after defaultProps are resolved, so typechecking will also apply to the defaultProps.
```

2017-07-02 18:40 UTC, merged

2017-07-03 03:39 UTC, btzr-io commented on src/components/button/index.js
> +        type: PropTypes.string.isRequired,
ok, anyway you merged this 🙃

2017-07-03 11:45 UTC, xaiki commented on src/components/button/index.js
> +        type: PropTypes.string.isRequired,
yeah, i put the explanation in the thread =P