TitleBar component
buttercomponents/butter-base-components pull request #9
Opened 2017-07-13 02:42 UTC by btzr-io

- Add TitleBar component.
- Update test.

2017-07-13 20:03 UTC, xaiki requested changes
a few nitpicks

2017-07-13 20:03 UTC, xaiki commented on src/index.js
> +            props.TitleBar.map((i, k) =>
this looks wrong, props should be lowercase

2017-07-13 20:03 UTC, xaiki commented on src/index.js
> +            {props.Dropdowns.text.map((i, k) => <Dropdowns.Dropdown key={k} {...i}/>)}
props should be lowercase

2017-07-13 20:03 UTC, xaiki commented on src/index.js
> +            {props.Dropdowns.color.map((i, k) => <Dropdowns.DropdownColor key={k} {...i}/>)}
ditto

2017-07-13 20:03 UTC, xaiki commented on test/data.js
> +        text: [{
why not make a list of dropdowns object with their type encoded ?

2017-07-13 20:03 UTC, xaiki commented on test/data.js
> +        text: [{
what does this have to do with this patch ?

2017-07-13 20:31 UTC, xaiki commented
merging navbar and toolbar seems odd, why would we want to re-render the whole navbar when we change a state in the toolbar ?

2017-07-13 21:34 UTC, btzr-io commented
`toolbar = navbar + action buttons`

2017-07-13 22:39 UTC, btzr-io commented on test/data.js
> +        text: [{
that's for `test`,  ( preview components )

2017-07-14 05:01 UTC, btzr-io commented
Anyway, we would need to use redux or flux to make everything work

2017-07-14 05:35 UTC, btzr-io commented on src/index.js
> +            props.TitleBar.map((i, k) =>
ok, fixed

2017-07-14 14:54 UTC, xaiki commented
> Navbar was just a wrapper for toolbar...
> Why would we want to re-render it? ^^
> `toolbar = navbar + action buttons`

because components re-render when props change
because pure-components check for their prop-changes before re-rendering.

2017-07-14 21:19 UTC, btzr-io commented
Ok, we also need `toolbar` outside `navbar` :upside_down_face:

2017-07-15 08:17 UTC, xaiki commented
looks good to me, do you need to fix the max button ?

2017-07-15 15:33 UTC, btzr-io commented
yes but I don't know how to do it yet :stuck_out_tongue:

2017-07-15 15:38 UTC, btzr-io commented
``` JS
win.on('maximize', function() {
  // make react component listen...
});
```

2017-07-15 15:51 UTC, btzr-io commented
but we aren't gonna use `title-bar` yet , so you can merge it

2017-07-15 19:37 UTC, btzr-io commented on index.js
>  let ActionBar = Navbar
what's that for? ^^

2017-07-15 23:23 UTC, xaiki commented on index.js
>  let ActionBar = Navbar
backward compatibility,
you should probably remove that now.
we use to call ActionBar Navbar, and the rest of the code depended on it.
now that you have a real navbar you should probably remove that hack.

2017-07-17 05:19 UTC, btzr-io commented on index.js
>  import React, { Component } from 'react';
We don't need to import react ^^

2017-07-17 05:22 UTC, xaiki commented on index.js
>  import React, { Component } from 'react';
are you sure ? did you try it without it ? i think the import react tweaks some bits in the import/export process.

2017-07-17 05:24 UTC, btzr-io commented on index.js
>  import React, { Component } from 'react';
yes, I don't see any errors :confused:

2017-07-17 05:25 UTC, btzr-io commented on index.js
>  import React, { Component } from 'react';
> the import react tweaks some bits in the import/export process.

so do we need it or not? ^^

2017-07-17 05:30 UTC, xaiki commented on index.js
>  import React, { Component } from 'react';
if you tested it and it works, we don't =P

2018-03-21 02:12 UTC, merged